### ISSUE TITLE
Use Youtube-dl json files and thumbnails where available.

### ISSUE THREAD

**Issue by ankenyr** [ankenyr/jellyfin-youtube-metadata-plugin#1]
This should be an option enabled in the plugin. If you are using the youtube-dl program you can ask it to save a copy of the metadata it found as a file and thumbnails. The json file is not the same as what is retrieved via the API.

**Comment by ankenyr** [comment]
This was requested by MrTimscampi in the jellyfind dev channel. Notes from that conversation.

"this one would be a different interface, ILocalMetadataProvider, that searches for json files"

**Comment by bpo5r5** [comment]
+1 this would be a great enhancement

**Comment by GlassedSilver** [comment]
This is great if you want to rebuild a library. Chances are there's always a bunch of videos that have been removed from YouTube as time passes. This way it's scrape once (when downloading) when the information is available for sure, re-use anytime you wish. Actual independence from YouTube relegating Google's servers to what they should be: a dumb pipe for content once, without any expectations of them keeping metadata around, which they will not for deleted videos.

**Comment by ankenyr** [comment]
This should be available per the latest version.
