### ISSUE TITLE
cant figure out the yt-dlp arguments required for the plugin

### ISSUE THREAD

**Issue by RobustMarker** [ankenyr/jellyfin-youtube-metadata-plugin#101]
Im using YoutubeDL material as it has a webgui on unraid. The issue im having is that I cannot figure out what arguments to have so I get the video ID in square brackets so the video can be identified in jellyfin. So far I have tried the id and --id arguments but I honestly have no idea what i am meant to do. 
<img width="897" alt="Screenshot 2024-03-20 at 00 10 40" src="https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/74292007/6f6a4d23-e4ea-49fe-a20e-ca6c368c56ef">
Here is a picture of what I am seeing and where im stuck.

**Comment by ankenyr** [comment]
The screenshot is not from my tool, not sure what I am looking at. Closing.
