### ISSUE TITLE
update for new version of jellyfin 10.9.0

### ISSUE THREAD

**Issue by gaming09** [ankenyr/jellyfin-youtube-metadata-plugin#102]
https://jellyfin.org/posts/jellyfin-release-10.9.0/  currently plugin shows as not supported

![image](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/31674130/95bbfa19-7e70-4bb0-9326-e1df41fc1db5)

**Comment by TheFrenchGhosty** [comment]
Can confirm @ankenyr 

Same stuff to update as when 10.7.0 updated I'm guessing?

**Comment by Herikc2** [comment]
I tried to build a new version but I received the following error:

- error NU1202: Package Jellyfin.Data 10.9.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Jellyfin.Data 10.9.0 supports: net8.0 (.NETCoreApp,Version=v8.0) 

But my .NET version is 8.0.4...

![image](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/42190622/bf52125d-d0f9-49a0-aaeb-bf5186cb5518)

**Comment by Herikc2** [comment]
> > Same stuff to update as when 10.7.0 updated I'm guessing?
> 
> Like are we just talking about bumping the Jellyfin Version in `Jellyfin.Plugin.YoutubeMetadata/Jellyfin.Plugin.YoutubeMetadata.csproj`
> 
> the line `<PackageReference Include="Jellyfin.Data" Version="10.8.0" />` It surely isn't going to be that simple??

Updated, I created a clean VM just to build a new release, the build was created normally but still is not compatible.

**Comment by SupertCZ** [comment]
I think you have to modify the targetAbi in the `build.yaml` file. It seems like 10.8 was backwards compatible with 10.7., however, 10.9.0 is not.

**Comment by Herikc2** [comment]
I tried and did not worked.

**Comment by Jchasa** [comment]
Hi, I was able to update everything and clear the errors with the sdk versions, but now I have this error and it is beyond my knowledge `Severity Code Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'IPluginServiceRegistrator' could not be found (are you missing a using directive or an assembly reference?)	Jellyfin.Plugin.YoutubeMetadata	C:\Users\USERNAME\Source\Repos\jellyfin-youtube-metadata-plugin\Jellyfin.Plugin.YoutubeMetadata\Plugin.cs	53	Active
`

**Comment by TheFrenchGhosty** [comment]
@Jchasa This might be helpful: https://github.com/jellyfin/jellyfin-plugin-dlna/commit/09a18668e48d12e9d1fe71aa52deca12ecc40a2a

(and basically all this since the last 6 months https://github.com/jellyfin/jellyfin-plugin-dlna/commits/master/ )

**Comment by ankenyr** [comment]
I see this, sorry that I have not given this plugin much love. I am currently building a company and have two kids, as long as the plugin works for me I don't pay much attention, I didn't even notice someone actually donated a few bugs to the koffi account until months later.

I will see if I can poke around at this soon because it will certainly affect me when I update to the latest version for the family media server.

**Comment by cdoucette** [comment]
There are a couple forks I see that have recent updates and mention 10.9 and when you compare with this base, say they could be merged cleanly at least. NET is not my thing so I can't really help more than that or really dig into it to make sure it all works.

Perhaps one of them could do a pull request for their required changes?

**Comment by nalsai** [comment]
I just got it working fully. I can make a PR soon. I'd also like to have #66 merged (I've personally been running my own custom build with it) and I'd like to take a look at #84.

**Comment by voltagex** [comment]
@nalsai can you make your PR? I just hit this issue too

**Comment by nalsai** [comment]
I've already made my PR and it has been merged. To use it, you need to download the latest pre-release and copy the following files to your jellyfin server into a subfolder of the plugins directory.

- "Jellyfin.Plugin.YoutubeMetadata.dll"
- "NYoutubeDLP.dll"
- "System.IO.Abstractions.dll"

or you can need to wait for a stable release to be made and added to the repo.

Alternatively, you can add my repo (`https://jellyfin-repo.nalsai.de/`) and install it from there. I have my own fork of the plugin there and am planning to make some more improvements.

**Comment by voltagex** [comment]
Thank you @nalsai!

**Comment by Jchasa** [comment]
> Thank you @nalsai!

Did you get it to work?

**Comment by ankenyr** [comment]
Things are updated to 10.9 and a new release should be available on my [repo](https://github.com/ankenyr/jellyfin-plugin-repo/blob/master/manifest.json). Thanks very much to @nalsai for the PR.

**Comment by micahmo** [comment]
Thanks so much for updating the plugin!

Is anyone else still getting `NotSupported`? Is this because I have a minor version bump (10.9.1)?

![image](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/7417301/1c62aed5-23c1-4c35-a5f1-b613a8091812)

![image](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/7417301/53829d1f-3c88-45fc-925d-a9a9f29be9af)
