### ISSUE TITLE
Failed to load assembly `codecoveragemessages.dll` after updating to 1.0.3.10

### ISSUE THREAD

**Issue by alpha-tango-kilo** [ankenyr/jellyfin-youtube-metadata-plugin#107]
Jellyfin server running 10.9.2 (based on the [LinuxServer docker image](https://github.com/linuxserver/docker-jellyfin), with `yt-dlp` installed), on a Debian bookworm host system

Tried uninstalling and reinstalling the plugin, no difference

On Jellyfin start-up I see this in the logs. The interface just says "Status Malfunctioned"

```
[12:11:59] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/data/plugins/YoutubeMetadata_1.0.3.10/CodeCoverage/codecoveragemessages.dll. Unknown exception was thrown. Disabling plugin
System.BadImageFormatException: Bad IL format. The format of the file '/config/data/plugins/YoutubeMetadata_1.0.3.10/CodeCoverage/codecoveragemessages.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
```

**Comment by TheFrenchGhosty** [comment]
The release zip wasn't cleaned: https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/releases/tag/1.0.3.10

It contains a lot of useless files generated during build.

If you want to fix yourself: in `YoutubeMetadata_1.0.3.10/` delete everything except `Jellyfin.Plugin.YoutubeMetadata.dll  meta.json  NYoutubeDLP.dll  System.IO.Abstractions.dll`

I contacted ankenyr about it

**Comment by alpha-tango-kilo** [comment]
Yep, that solved it, thanks! Interestingly, in Jellyfin's UI it now reports I'm using YoutubeMetadata 1.0.4.0 🤔

**Comment by bigboigahoy** [comment]
> Yep, that solved it, thanks! Interestingly, in Jellyfin's UI it now reports I'm using YoutubeMetadata 1.0.4.0 🤔

This seems to be the case for me as well.

**Comment by ankenyr** [comment]
Already working on this, not sure what happened but I am moving things to a dev container and using jellyfins jprm module to manage the repository. It should make things easier to manage in the future.

**Comment by ankenyr** [comment]
Ok 1.0.3.12 is out. I had some issues and to prevent anyone who may have downloaded one of the bad versions I  incremented the number a few times.

**Comment by ankenyr** [comment]
Also thanks to @TheFrenchGhosty for the help in troubleshooting.

**Comment by TheFrenchGhosty** [comment]
Just something to note: the task that update the plugin might not work, if so, you have to go find the plugin in the plugin catalog, install the new version, and go back to the installed plugin list, and uninstall the old version.

We spent like an hour trying stuff to avoid that, but nothing has worked, my guess is that because .10 is marked as "malfunctioned" Jellyfin isn't able to update it.

**Comment by alpha-tango-kilo** [comment]
Thanks both! Manually sorted 1.0.3.12 and it's looking good 😃

**Comment by TheFrenchGhosty** [comment]
@alpha-tango-kilo perfect :)
