### ISSUE TITLE
Question: Is the filename in the following format (position of youtube video ID) also accepted?

### ISSUE THREAD

**Issue by lamyergeier** [ankenyr/jellyfin-youtube-metadata-plugin#111]
We can see in the following image the filename is in this format `Title.[0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9].ID.Extension` (i.e. ID is just before extension delimited by a dot. And the Jellyfin UI shows YouTiube and Director Hyperlinks as follows (2nd image). 

**Question: Is this format also accepted?**

Note: I have info.json file at the same path with the above filename pattern

![image](https://github.com/user-attachments/assets/e48ce6a9-5743-4044-a078-9f0092ffd269)

![image](https://github.com/user-attachments/assets/184e9a23-4a8f-45e0-874e-459f1317079b)

**Comment by ankenyr** [comment]
No that is not a format that I support at this point.

**Comment by lamyergeier** [comment]
@ankenyr  Thanks, but I didn't create those metadata. And I am confused how it got created even though it doesn't match your format.
