### ISSUE TITLE
Jellyfin showing plugin is Not Supported

### ISSUE THREAD

**Issue by onword** [ankenyr/jellyfin-youtube-metadata-plugin#114]
I installed the plugin and the installation went fine, however after rebooting the server the plugin shows as "Not Supported" and is unavailable to select as a metadata source. I'm running Jellyfin server in docker on a Synology NAS. Doesn't seem to matter if it's via the repository installation or manual. How can I fix this?

**Comment by ankenyr** [comment]
What version of Jellyfin are you on?

**Comment by onword** [comment]
10.9.0

**Comment by ankenyr** [comment]
Can you upgrade to `10.9.3` I believe there were incompatibilities made with plugins in the early 10.9's

**Comment by onword** [comment]
Sorry, I'm not sure if I had a typo or not, but I just used the repository/catalog in Jellyfin again to install 1.0.3.9 and it's the same issue. After rebooting Jellyfin (through the Jellyfin Dashboard), the plugin just says "Not Supported".

**Comment by onword** [comment]
I've moved to a different solution, resolving this thread. Thank you.
