### ISSUE TITLE
Pictures aren't pulled automatically for new videos

### ISSUE THREAD

**Issue by TheFrenchGhosty** [ankenyr/jellyfin-youtube-metadata-plugin#17]
When adding new videos to my collection, the metadata will be correctly obtained, but the pictures will not, the only way to get them is to refresh the metadata / replace existing images.

**Comment by ankenyr** [comment]
Are you using local json files for the metadata or remote? Got any logs that could help with this?

**Comment by TheFrenchGhosty** [comment]
Locale, and there is nothing in the log.

**Comment by ankenyr** [comment]
Is the picture blank or jellyfins subsitute picture? Are you on the latest version of the plugin? Version of jellyfin?

**Comment by TheFrenchGhosty** [comment]
>Is the picture blank or jellyfins  picture

Substitute

>Are you on the latest version of the plugin?

Yes

>Version of jellyfin?

10.6.3

**Comment by ankenyr** [comment]
Fixed with https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/commit/5c64e4c9f5d9f0d64dd2f6e0c4cc340ab2cd653e
