### ISSUE TITLE
Allow Collection field to be filled by Channel Name

### ISSUE THREAD

**Issue by NotExpectedYet** [ankenyr/jellyfin-youtube-metadata-plugin#19]
No idea if this is at all possible but just thought it would be cool to utilize the Collection field on my library. 

Currently my Youtube library is a single directory pointed at my youtube-dl output folders which loads 10000's of videos and there is currently no filter I can see on Jelly fin for Director.  

I gather this might be an alternative to tv show library option request as sorting by date pretty much accomplishes this inside of a collection just without any seasons.

**Comment by ankenyr** [comment]
You may want to look at my smart playlist plugin.
https://github.com/ankenyr/jellyfin-smartplaylist-plugin
This gives you the ability to provide queries which include the director and other fields to create playlists. I use it to keep playlists for each channel and filter by unwatched. As I watch videos they get removed. Would this satisfy your need?

**Comment by NotExpectedYet** [comment]
> 
> 
> You may want to look at my smart playlist plugin.
> https://github.com/ankenyr/jellyfin-smartplaylist-plugin
> This gives you the ability to provide queries which include the director and other fields to create playlists. I use it to keep playlists for each channel and filter by unwatched. As I watch videos they get removed. Would this satisfy your need?

It sounds like it would certainly, I will check it out thanks!

**Comment by NotExpectedYet** [comment]
Just wanted to reply back as I've had chance to try the plugin you made and recommended. 

First, Works great! Took 20 seconds and it had created a playlist for me. 

Thanks, I gather if you've no plans to add in the collection field then might as well close this. 

![image](https://user-images.githubusercontent.com/61137988/94812608-dd9bb100-03ee-11eb-8c7b-eba5f8048579.png)

**Comment by ankenyr** [comment]
I do not have plans and will close this. I don't feel that the metadata agent should be managing collections. Making collections for each channel may not be something everyone would want. Without a clear understanding of how this could be integrated without interfering with others desires and making it generalizable to possibly other fields people may want overloaded I won't be working on this. The smart playlist is also a more appropriate place for managing playlists or collections.

Thanks for the kind words. If you have any other feature requests for this or the smart playlist plugin please reach out!
