### ISSUE TITLE
Clarifications regarding info.json/description-files from youtube-dl

### ISSUE THREAD

**Issue by davralin** [ankenyr/jellyfin-youtube-metadata-plugin#20]
I see #1 mention using the local files populated by youtube-dl if you add `--write-description --write-info-json` as a metadata-source if present.

I am however a little unclear if that would still require the files to be named with the ID in the name or not.

I alredy have a fairly huge library downloaded from youtube, I do have the json/description-files, but I don't have the ID in the name.

**Comment by ankenyr** [comment]
https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/blob/800669a5ab59cbb66259c87c5c9b0988c54f9aa3/Jellyfin.Plugin.YoutubeMetadata/Providers/YoutubeLocalProvider.cs#L46

It will look for the same file name but just swap out the extension.
so the file
20180302-Why_is_pi_here_And_why_is_it_squared_A_geometric_answer_to_the_Basel_problem [d-o3eB9sfls].webm
will need an info json file
20180302-Why_is_pi_here_And_why_is_it_squared_A_geometric_answer_to_the_Basel_problem [d-o3eB9sfls].info.json

This should be how youtube-dl works out of the box and thus should not require any modifications to your library.

**Comment by davralin** [comment]
No, youtube-dl by defaults doesn't have brackets around the id, for instance:
```
$ youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --get-filename
youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.mp4
```

I have, anyway, modified my output-template to not include the id, as it seemed meaningless to include, since the id is still intact in the json-file.

I'm a little confused about your example, would the following give me a hit:
```
$ youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --get-filename -o '%(title)s.%(ext)s' --write-info-json
youtube-dl test video ''_ä↭𝕐.mp4
```
since that will add a info.json named according to the file, but without containing the id in the filenames?

**Comment by ankenyr** [comment]
Ahh yes, the brackets are added by me using the templating function. This
style was taken by the original Youtube metadata agent I used when I was
using Plex. It has been a while since I had taken a look at my download
script.

The name of the media file and the info.json file need to be the same and
to ID it currently uses a regex to find the is within the brackets. So to
use this you will need to adopt that style. You could also make a PR to add
in the ability to provide your own regex or wait until I have time to
implement that myself.

Let me know what you think or if I missed any questions.

**Comment by davralin** [comment]
Thanks for answering, unfortunately - I have almost 20k files downloaded - renaming isn't that feasible, nor wanted - id's give nothing to the name, and the metadata is right beside the file if I ever want it.

I'll keep an eye on this for any future enhancements. :-)

**Comment by NotExpectedYet** [comment]
> Thanks for answering, unfortunately - I have almost 20k files downloaded - renaming isn't that feasible, nor wanted - id's give nothing to the name, and the metadata is right beside the file if I ever want it.
> 
> I'll keep an eye on this for any future enhancements. :-)

I'm in the same situation after re-configuring my library and completely ignoring the id field. 

I'm tempted to write a script that will run over my downloads directory, look for info.json files and then append those to the matching file names. Would this be of interest? I'm not making a promise, it's just on my list of stuff to do aha

**Comment by davralin** [comment]
I'm sure it will be of interest to someone - I did however end up ditching jellyfin, then re-downloading everything - but this time I added the ID to the name BUT I embedded the json-file into the MKV (as that is supported for MKV-containers).

Just a couple of weeks ago, I started looking at jellyfin again, and noticed that embedded json-files are not supported either. :-D
