### ISSUE TITLE
Plugin Repository

### ISSUE THREAD

**Issue by Maxplosion** [ankenyr/jellyfin-youtube-metadata-plugin#22]
Hi, 

are there any plans to create a plugin repository for this? ( or if not maybe add it to an existing one (official or 3rd party)?  https://jellyfin.org/docs/general/server/plugins/index.html )
It's a lot easier to just add a repo to jellyfin and always have up-to-date versions of the plugins instead of manually adding the files to the plugin file directory every time a new update is released. (especially tedious with multiple plugins) 

Thanks!

**Comment by TheFrenchGhosty** [comment]
Would be amazing, and it's easy to do on Github, example: https://github.com/danieladov/JellyfinPluginManifest

**Comment by lmgarret** [comment]
There's already one: `https://raw.githubusercontent.com/ankenyr/jellyfin-plugin-repo/master/manifest.json` (see [this comment](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/23#issuecomment-790368143) from the maintainer). I can confirm it's working properly :)

**Comment by TheFrenchGhosty** [comment]
@lmgarret Yeah, same, I've been using it since 10.7 came out.

@ankenyr You should definitely mention it in the readme!

**Comment by ankenyr** [comment]
Added to the readme.
