### ISSUE TITLE
Support for 10.7.0

### ISSUE THREAD

**Issue by krutburken** [ankenyr/jellyfin-youtube-metadata-plugin#23]
Is this planned? 1.0.2.2 currently errors out when loading on 10.7.0-rc1

**Comment by ankenyr** [comment]
I have not had a chance to look at the latest version of jellyfin. Can you provide me the errors it shows? I am busy with work at the moment but should have some time freed up in the next few weeks to do this. Others are welcome to provide fixes for me to merge in.

**Comment by krutburken** [comment]
No problem. I don't have 10.7.0 installed currently but I found part of the error in my clipboard:

`[18:02:44] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error loading types from Jellyfin.Plugin.YoutubeMetadata, Version=1.0.2.2, Culture=neutral, PublicKeyToken=null.`
 
I'll see if I can get the whole thing for you later today. Unfortunately I don't know C# so I can't really help with the code. You can find some Plugin developer notes for 10.7.0 here though: https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0-rc1

**Comment by ankenyr** [comment]
I don't know C# too well myself ;) These plugins were my first attempt with C#.
Thanks for the pointers on the dev notes.

**Comment by krutburken** [comment]
Managed to get it working with google and some jf-documentation :) https://github.com/krutburken/jellyfin-youtube-metadata-plugin/commit/051b32266aa0ca870fd6978ac73d2f7d0b65a929

Let me know if you want a pr on it

**Comment by ankenyr** [comment]
Sure!
Looking at the code right now it looks good. Please try to change as little in the csproj file as possible. I don't think you need the target framework changed to net5.0, I also don't think you need Microsoft.Extensions.Http. Please try to adopt my whitespace also.

**Comment by krutburken** [comment]
According to the docs you actually do now:
"Plugins must now target net5.0" (from https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0-rc1)

And `IHttpClient` has been removed from MediaBrowser so you need to use `IHttpClientFactory` instead, which is from Microsoft.Extensions.Http. Ah yes, my editor messed it up.

 Thanks for the motivation to look into c# :)

**Comment by TheFrenchGhosty** [comment]
@ankenyr I tested latest master on 10.7.0rc3 and can confirm that it works.

Can you provide a release for it? Is anything missing?

**Comment by ankenyr** [comment]
Had some issues getting 10.7 launched in my test environment when I tried. I have not had time to sit down and figure out due to work being very hectic right now. I have a vacation coming up where I plan to work on my plugins and other personal projects.

**Comment by TheFrenchGhosty** [comment]
@ankenyr Mmh weird, I didn't have any issue.

Let's hope you can figure out the issue quickly, so that you can actually enjoy your vacation.

**Comment by krutburken** [comment]
I've been using it on 10.7.0-rc1-3 without issues too.

**Comment by ankenyr** [comment]
This should be good. Had a chance to finally sit down and look into things. Seems yarn is borked on my machine giving me some weird error.

```
 yarn install
info No lockfile found.
[1/4] Resolving packages...
warning epubjs > @types/localforage@0.0.34: This is a stub types definition for localforage (https://github.com/localForage/localForage). localforage provides its own type definitions, so you don't need @types/localforage installed!
warning stylelint-config-rational-order > stylelint > postcss-markdown > remark > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
warning stylelint-config-rational-order > stylelint > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning stylelint-config-rational-order > stylelint > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning stylelint-no-browser-hacks > stylehacks > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning workbox-webpack-plugin > workbox-build > @hapi/joi@16.1.8: Switch to 'npm install joi'
warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
[2/4] Fetching packages...
error @babel/eslint-parser@7.13.8: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || >=14.0.0". Got "13.12.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Not sure why this is happening since I never use yarn or npm but a --ignore_engines flag got me passed the error.

I have also updated my plugin repository located at `https://raw.githubusercontent.com/ankenyr/jellyfin-plugin-repo/master/manifest.json`
