### ISSUE TITLE
Which resulting file should be placed in the directory?

### ISSUE THREAD

**Issue by 7596ff** [ankenyr/jellyfin-youtube-metadata-plugin#3]
I'm following the steps in readme, but step 4 is very vague. After running `dotnet publish`, there are a lot of dll files in `bin/`. I am not familiar with the dotnet build process. Could you please elaborate on which file should be placed in `data/plugins/YoutubeMetadata`? Thank you.

**Comment by ankenyr** [comment]
It should be all of them if we both did things correctly. I included a list of the files in the release
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2020-04-12 22:47   YoutubeMetadata/
   123392  2020-04-02 10:45   YoutubeMetadata/Google.Apis.Auth.dll
     5120  2020-04-02 10:45   YoutubeMetadata/Google.Apis.Auth.PlatformServices.dll
    73216  2020-04-02 10:45   YoutubeMetadata/Google.Apis.Core.dll
    78848  2020-04-02 10:45   YoutubeMetadata/Google.Apis.dll
   293888  2020-04-06 08:12   YoutubeMetadata/Google.Apis.YouTube.v3.dll
    17408  2020-04-12 22:47   YoutubeMetadata/Jellyfin.Plugin.YoutubeMetadata.dll
   693680  2019-11-09 01:56   YoutubeMetadata/Newtonsoft.Json.dll
---------                     -------
  1285552                     8 files

Are you seeing a different set of files than the ones above in your bin directory?

**Comment by 7596ff** [comment]
I had initially ran `dotnet publish --configuration Release --output bin` in the root of the repository. After running it inside `Jellyfin.Plugin.YoutubeMetadata`, I have achieved your result. 

While installing the plugin, I realized the `plugins` directory is actually in the root of `/var/lib/jellyfin`: 
```
[cassie@forretress jellyfin]$ ls -al /var/lib/jellyfin/
total 28K
drwxr-xr-x 4 jellyfin jellyfin 4.0K Apr 16 13:16 config
drwxr-xr-x 5 jellyfin jellyfin 4.0K Apr 16 21:25 data
drwxr-xr-x 2 jellyfin jellyfin 4.0K Apr 16 13:15 log
drwxr-xr-x 5 jellyfin jellyfin 4.0K Apr 16 13:27 metadata
drwxr-xr-x 4 jellyfin jellyfin 4.0K Apr 16 21:24 plugins
drwxr-xr-x 3 jellyfin jellyfin 4.0K Apr 16 13:16 root
drwxr-xr-x 3 jellyfin jellyfin 4.0K Apr 16 13:16 .aspnet
```
Placing `YoutubeMetadata` in that folder actually caused it to appear in Jellyfin. I will create a pull request to update the readme, if that is okay.

**Comment by ankenyr** [comment]
Feel free to always send a PR. We can work through any details on there. One thing to be aware of, specific paths may not be valid across all platforms and implementations. My path to the plugin directory is /opt/jellyfin/data due to running in docker and /opt/jellyfin being a mount point.

**Comment by ankenyr** [comment]
This was resolved in the first PR! Thanks for sending that @7596ff !
