### ISSUE TITLE
Jellyfin 10.8 Not Supported

### ISSUE THREAD

**Issue by 17hoehbr** [ankenyr/jellyfin-youtube-metadata-plugin#30]
I'm trying to get this plugin to work on the latest unstable docker image (Jellyfin 10.8) and am getting a status message that says Not Supported. I'm not sure if there are any logs or anything that I could upload but I would really appreciate getting this working with the unstable build since it dramatically decreases loading times.

**Comment by ankenyr** [comment]
Are you trying to install this via the repositories or manual? If not
manual have you tried that way?

**Comment by 17hoehbr** [comment]
At first I tried the repository and when that didn't work I tried building it myself. Both methods gave me the same error.

**Comment by ankenyr** [comment]
I suspect it may be incompatible with 10.8. IIRC they removed some json libraries which I am using and I have yet to move away from those.

If you could, look through your logs for any error messages. That should confirm for me if that is indeed the problem or if there are possibly other issues I will need to take care of before 10.8 is out for general release.

**Comment by 17hoehbr** [comment]
This is the error message I found in the logs. It seems like the other included .dll files are all loading fine but YoutubeMetadata.dll is having issues with getting images.

>[2021-06-08 18:27:28.755 -04:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/YoutubeMetadata_1.0.3.3/Jellyfin.Plugin.YoutubeMetadata.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.TypeLoadException: Method 'GetImages' in type 'Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider' from assembly 'Jellyfin.Plugin.YoutubeMetadata, Version=1.0.3.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()

**Comment by krutburken** [comment]
@ankenyr  Just tried this on the new 10.8.0-alpha1 release and this plugin is indeed broken

**Comment by ankenyr** [comment]
Latest plugin is now compatible with 10.8
