### ISSUE TITLE
Feature Request: Group into Channels

### ISSUE THREAD

**Issue by MatthK** [ankenyr/jellyfin-youtube-metadata-plugin#33]
I just installed the Plugin and it does work fine in pulling the metadata from Youtube.

However I have quite a lot of content downloaded from various channels. Now there are some 600+ youtube videos in one big library, all mixed together.

Would it be possible to group them by channel, a bit like TV Shows, where a channel could even be grouped into Seasons (year?) and Episodes?

**Comment by PrplHaz4** [comment]
Sounds the same or similar to https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/7

**Comment by ankenyr** [comment]
Yup, this is the same as #7 unless @MatthK can specify why it is different. Going to close this. The code in Jellyfin was implemented in 10.8 and will be available once that is released unless you compile it yourself.
