### ISSUE TITLE
Can plug-in identify show name

### ISSUE THREAD

**Issue by psyciknz** [ankenyr/jellyfin-youtube-metadata-plugin#34]
I just started using and attached to a mixed content library.  Not realising that tv shows were not yet supported.

I'm populating a folder from tubesync and are using a YouTube id but not in square brackets.   I do also have nfo which is I assume where the plug-in is getting episode information from.

My question is how can I populate the "show" name which is each directory the episodes are stored in. 

Generally
Video\cityplannerplays\showepispde.mkx
I have also got the ability to set the "show name" with a YouTube channel Id (starting UC)

**Comment by ankenyr** [comment]
Started reading up on tubesync, seems like a nifty tool I might adopt myself. It does not allow you to provide its own templating per the youtube-dl templating? My plugin currently requires that the ID appear in the file name inside the square braces.

**Comment by ankenyr** [comment]
Hi @psyciknz 
TV shows are now supported on 10.8 with some modifications I made in Jellyfin and this plugin. If you update I think you will be very happy with the results.
