### ISSUE TITLE
My year based season folders cause episode title and description to be repeated

### ISSUE THREAD

**Issue by NotExpectedYet** [ankenyr/jellyfin-youtube-metadata-plugin#38]
Hello, me again :) 

I've finally got my library scanned and it seems I've got repeated episode names and titles. They look to be taking a random episode (couldn't see a pattern) from the season folder and re-applying that ID for all episodes in that season folder. 

Things I've tried: 
Remove all local .nfo files (they did originally have the names set as this, probably from my first scan before the allowance for my specific folder structure)
Multiple library refreshes with replace images and meta data turned on. 
Deleting the library and re-adding. 
Double checked the ID's in the file names we're indeed matched correctly, and also resulted in the correct youtube video when accessed (didn't trust my script at first aha)

Doesn't seem to be Jellyfin as it's not done this for any other folders. 

Additionally they're called episode 1, and have "1." prepended to the title. Gather that's Jellyfin and my date based episode format.

**Comment by NotExpectedYet** [comment]
Seems to be certainly when an ID is grabbed by the plugin. I've just checked another series that is from Odysey as those don't get picked up by your regex for the ID and that's all got the correct episode names.

**Comment by ankenyr** [comment]
Can you provide a couple of the info.json and the file names (they are in
the image but it would be easier for me to copy/paste.

**Comment by NotExpectedYet** [comment]
[2022.zip](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/files/7875453/2022.zip)

There's my 2022  folders info.jsons. 

Those all got added as which is the 3rd in the series. 
![image](https://user-images.githubusercontent.com/61137988/149631192-52a1687a-3d56-4fb2-9cdd-0164c804f473.png)

**Comment by HeliosLHC** [comment]
Jellyfin Version: 10.8.0 on x64 Linux
Plugin Version: 1.0.3.3 <-> 1.0.3.5

Sorry to tack on to the issue but I can report that I am experiencing the same problem where it seems a random video is chosen from the folder and it's metadata is applied to all other videos in the folder. 
[yt_metadata_plugin_issue.zip](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/files/7875732/yt_metadata_plugin_issue.zip)


My structure is the following:
```
CHANNEL_NAME_1 [CHANNEL_ID_1]
   VIDEO_NAME_1 [VIDEO_NAME_1_ID].webm 
   VIDEO_NAME_1 [VIDEO_NAME_1_ID].info.json
   VIDEO_NAME_1 [VIDEO_NAME_1_ID].webp
   VIDEO_NAME_2 [VIDEO_NAME_2_ID].webm 
   VIDEO_NAME_2 [VIDEO_NAME_2_ID].info.json
   VIDEO_NAME_2 [VIDEO_NAME_2_ID].webp
CHANNEL_NAME_2 [CHANNEL_ID_2]
...
...
```
I have attached sample info.json files and thumbnails along with a file structure txt file.

When I force refresh the metadata on the library it appears to correct the duplicate metadata issue but after some time, the plugin seems to refresh the metadata and in turn re-introduce the duplicate metadata across all the videos in each channel folder.

**Comment by ankenyr** [comment]
@NotExpectedYet It looks like your content is getting hit because it is conflicting with the the naming scheme of [Jellyfin](https://jellyfin.org/docs/general/server/media/shows.html)

Debugging I can confirm that my plugin is returning the correct information from the json and is retrieving the correct json. Specifically I removed the S0 from the file names.

**Comment by ankenyr** [comment]
@HeliosLHC I think your issue is similar, I removed the prefixing abbreviation of the channel name and it looks to work for me. My plugin is returning the correct information so I believe something within Jellyfin, namely its episode/season number detecting mechanisms are the culprit. Do you see this with other folders that have the same prefixing channel name?

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet It looks like your content is getting hit because it is conflicting with the the naming scheme of [Jellyfin](https://jellyfin.org/docs/general/server/media/shows.html)
> 
> Debugging I can confirm that my plugin is returning the correct information from the json and is retrieving the correct json. Specifically I removed the S0 from the file names.

Dammit aha. What did you mean by removing the S0 from the file names sorry? 

Currently I have `{CHANNEL NAME}/{YYYY}/{CHANNEL NAME} - {YYYY}-{MM}-{DD} - {TITLE} [{ID}]`

Going by your readme I should just have to change to:
3Blue1Brown - 20211023 - A_few_of_the_best_math_explainers_from_this_summer
`{CHANNEL NAME}/{YYYY}/{CHANNEL NAME} - {YYYY}{MM}{DD} - {TITLE} [{ID}]`

**Comment by NotExpectedYet** [comment]
Can I add a feature request for this plugin to generate the year folders as an option? No rush for it like, I'm going to be moving all my stuff out of a folder to conform with the current plugin requirements on naming anyway so this specific issue for me can be closed.

**Comment by ankenyr** [comment]
Right after the underscore in the file names is S0 which is causing the
problem for Jellyfin, not the plugin.

I don't want my plugin to be messing with people's file system and
reorganizing things. That seems like it might surprise people and possibly
mess up their system. There is a plugin for auto organizing already which
may be of help.
https://github.com/jellyfin/jellyfin-plugin-autoorganize

**Comment by NotExpectedYet** [comment]
I was meaning virtually as you did before with season 1.

**Comment by ankenyr** [comment]
I don't think so as it would conflict with the natural season naming in the file system. I don't know enough about the internals to jellyfin to know how this would affect things. We already see some bugs where a season gets all episodes renamed to the first episode in the season which seems to be due to the internal providers getting confused,

**Comment by matthewcen** [comment]
@ankenyr I removed the channel name before the dash in the channel folders, and it seems the issue appears to be resolved.

Example.
```
Channel_Name - [Channel_ID]
# became the following
[Channel_ID]
```

**Comment by HeliosLHC** [comment]
@ankenyr 

Hi, this issue appears in other folders that have the same naming scheme. It appears that your recommendation or removing the channel name from the folder name eliminated the issue.

**Comment by NotExpectedYet** [comment]
> I don't think so as it would conflict with the natural season naming in the file system. I don't know enough about the internals to jellyfin to know how this would affect things. We already see some bugs where a season gets all episodes renamed to the first episode in the season which seems to be due to the internal providers getting confused,

Must still do something else with those as I've all providers turned off apart from youtube. No trouble and thanks for the explanation.
