### ISSUE TITLE
Music metadata not provided

### ISSUE THREAD

**Issue by e4xo** [ankenyr/jellyfin-youtube-metadata-plugin#45]
Metadata is not provided for music libraries.

I'm using jellyfin 10.8.0-beta2 and plugin version 1.0.3.5.

These are my library settings:
![2022-04-22-145737_808x898_scrot](https://user-images.githubusercontent.com/103189551/164718883-fa6a7389-72de-4104-8373-299e55b5642f.png)

Files are in subfolders with the channel/playlist name, all files are owend by the jellyfin user and are using the following format:
```
'ukfdrumandbass/2021-11-11_ukfdrumandbass_amc-brazil_[i5t3FlmDJvw]_opus.info.json'
'ukfdrumandbass/2021-11-11_ukfdrumandbass_amc-brazil_[i5t3FlmDJvw]_opus.jpg'
'ukfdrumandbass/2021-11-11_ukfdrumandbass_amc-brazil_[i5t3FlmDJvw]_opus.nfo'
'ukfdrumandbass/2021-11-11_ukfdrumandbass_amc-brazil_[i5t3FlmDJvw]_opus.ogg'
```

But no metadata is provided in jellyfin and they are displayed like this:
![2022-04-22-152222_471x32_scrot](https://user-images.githubusercontent.com/103189551/164722957-5cadec16-3572-48cc-83a1-c98c00082414.png)

[meeb/tubesync](https://github.com/meeb/tubesync) is used to download the files.

**Comment by ankenyr** [comment]
Support is only for Music Videos not Music. Is YouTube the best place for
getting metadata for a song or album? Musicbrainz should cover everything
and would be surprised to find something not existing in there.

**Comment by e4xo** [comment]
Okay thank you, I will try that.
