### ISSUE TITLE
Status: NotSupported

### ISSUE THREAD

**Issue by Brancliff** [ankenyr/jellyfin-youtube-metadata-plugin#49]
In my Admin Dashboard > Advanced > Plugins, the YouTubeMetadata plugin's status is listed as "NotSupported" instead of "Active". Because of that, YouTube isn't listed as a metadata provider source in the library settings.

Jellyfin version: 10.8.0 Beta, Docker
YouTube Metadata version: 10.3.6

**Comment by Dynamic-Gravity** [comment]
@ankenyr thanks for the follow up. :)
