### ISSUE TITLE
Add Music Video library support

### ISSUE THREAD

**Issue by GameMaster2030** [ankenyr/jellyfin-youtube-metadata-plugin#5]
Could there be an ID field in the identify tab of a video?
Also, how should the file be called? The Youtube-dl name? Only the video title? The id? Please clarify this in the readme.
Could support be added to a Music Video library?

**Comment by GameMaster2030** [comment]
Figured out how they need to be called now, it needs to have the id between brackets: [ID]. Please add that to the readme

**Comment by ankenyr** [comment]
>Could there be an ID field in the identify tab of a video?
Yes I had planned on doing this soon. Will create a PR specifically for that.
>Also, how should the file be called? The Youtube-dl name? Only the video title? The id? Please clarify this in the readme.
Will add this to my next push
>Could support be added to a Music Video library?
Not sure what is lacking to make it available for a Music Video library. Does it not appear on the list of available metadata downloaders?

**Comment by ankenyr** [comment]
Made issue #6 to track the ID issue.

**Comment by GameMaster2030** [comment]
Ok, thanks! 
> Not sure what is lacking to make it available for a Music Video library. Does it not appear on the list of available metadata downloaders?
Yeah, I can't see it on the list

**Comment by mistergoodwin** [comment]
Sorry to piggyback.
> make it available for a Music Video library

+TV Shows library too.

It currently only shows up for the Movie library.
Thanks so much for getting it this far.

**Comment by ankenyr** [comment]
This issue is starting to get overloaded. @mistergoodwin would you mind making a separate issue for TV shows? I have a few follow up questions on how that could or should be implemented.

@GameMaster2030 Is there anything left in this request besides enable the plugin for Music Videos? If not I will change the title to reflect that.

**Comment by GameMaster2030** [comment]
Yeah, that's the only thing

**Comment by ankenyr** [comment]
Sorry that took so long, got really busy at work. Just added this as a feature. Please file a new issue if you find any problems.
