### ISSUE TITLE
All the video have same image

### ISSUE THREAD

**Issue by kr521** [ankenyr/jellyfin-youtube-metadata-plugin#59]
jellyfin: build from linuxserver/jellyfin:10.8.0 with yt-dlp 2022.06.29
plugin: 1.0.3.8

![1B1EE69C-CC09-44A8-9B1B-53FF6391CEC5](https://user-images.githubusercontent.com/3262751/177079308-c5d08e4e-c9b8-4211-845c-bc238f95b3ce.png)

youtube file list 
<img width="1003" alt="WX20220704-115826@2x" src="https://user-images.githubusercontent.com/3262751/177079243-37822c16-0087-46c1-8789-27499af79668.png">

jellyfin log error 
<img width="1426" alt="WX20220704-104855@2x" src="https://user-images.githubusercontent.com/3262751/177079276-b93c3be1-3a38-4bdd-aa6b-a6597143692d.png">

**Comment by ankenyr** [comment]
Those errors are not from the plugin.

Do other channels have the same effect or only this one? Is there anything special about this channel and its directory in comparison to others? Can you turn on debug logging and provide the logs while you refresh metadata and images for that channel?

**Comment by kr521** [comment]
1. all the channels with youtubemeta have the same effect 
I was try to no have info json file in the directory , but have the same effect.

3. directory and file permission list in file 
[filelist.txt](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/files/9042870/filelist.txt)

4. debug log 
[jellyfin.debug.log](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/files/9042872/jellyfin.debug.log)

**Comment by ankenyr** [comment]
Is this a movie or a show library type?

**Comment by kr521** [comment]
> Is this a movie or a show library type?

movie type.

**Comment by kr521** [comment]
> 

Thank you for you response

1. all the video downloaded from same channel with yt-dlp . the video download from  : https://www.youtube.com/c/AnglersAll/videos
2. all the video in one directory with name of channels author. when i was add this to jellyfin library the content type is movie
3. i was try to set the content type with show , but have the same question ,all the video with the same primary .
4. when i do sacan all libraries , all the video have the same primary. but when i select one video and use edit images , i can download the right primary with youtubemetadata.
5. I was try to down the jellyfin version to 10.7.7 with youtube-metadata-plugin , all is work , but the primary is not the right primary .

**Comment by ankenyr** [comment]
Sorry I don't quite understand 5. You downgraded to 10.7.7 and the plugin works fine or not?

**Comment by kr521** [comment]
> Sorry I don't quite understand 5. You downgraded to 10.7.7 and the plugin works fine or not?

down to 10.7.7 with metadata plugin version 1.0.3.3 , the plugin is work .

**Comment by kr521** [comment]
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/3262751/178108880-39bbf361-e06d-427e-9643-ccaf80831cb2.png">
same setting in 10.7.7 and plugins version 1.0.3.3

**Comment by ankenyr** [comment]
Just following up, has this been resolved with my last release?

**Comment by Imroothomelab** [comment]
Im currently having the same problem, running latest plugin version and jellyfin 10.8.4 on windows, I made sure the naming for the .json, thumnail and media file are same with the ID within square brackets, I have been looking for jellyfin v 10.7.7 to try it but cant find where to download, any tricks that can help? 

thx

**Comment by Imroothomelab** [comment]
> Im currently having the same problem, running latest plugin version and jellyfin 10.8.4 on windows, I made sure the naming for the .json, thumnail and media file are same with the ID within square brackets, I have been looking for jellyfin v 10.7.7 to try it but cant find where to download, any tricks that can help?
> 
> thx

never mind, found the problem, the thumbnail format was on default .webm , change to .jpg now works fine

**Comment by ksyasuda** [comment]
> never mind, found the problem, the thumbnail format was on default .webm , change to .jpg now works fine

How were you able to change the default format from .webm to .jpg?  I'm having the same issue and have not figured out how to change the default

**Comment by ankenyr** [comment]
Sorry, I do t understand 5. You downgraded and it worked as you expected?

**Comment by Routhinator** [comment]
> How were you able to change the default format from .webm to .jpg? I'm having the same issue and have not figured out how to change the default 

Bump, this needs an answer - how is this done. Webp does not work properly with Jellyfin.
