### ISSUE TITLE
Plugin page loads endlessly

### ISSUE THREAD

**Issue by PascalMinder** [ankenyr/jellyfin-youtube-metadata-plugin#62]
Is it normal that the plugin page has an endless spinner on it?

![image](https://user-images.githubusercontent.com/1893516/181098400-9ec5b8d2-110a-4b05-9f5d-79fb051e71f5.png)

**Comment by ankenyr** [comment]
Seems that commenting out html doesn't actually comment it out? Either way I have removed that permanently. It will be out in the next release.
