### ISSUE TITLE
Youtube-dl not found on path - Youtubedl-material

### ISSUE THREAD

**Issue by LukeG20** [ankenyr/jellyfin-youtube-metadata-plugin#64]
Hi,

I'm getting a "youtube-dl not found on path!" error when trying to use the plugin. I'm guessing that's because I'm using "Youtubedl-material" rather than directly using "yt-dlp" is there anyway I can get the plugin to pickup the instance of "yt-dlp" that "Youtubedl-material" is using?

**Comment by ankenyr** [comment]
How did you install material? The instructions mention doing a pip install <package> so if you used yt-dlp it should be in the common location and in your path.

**Comment by ankenyr** [comment]
I don't quite understand. Is Material and jellyfin both in the same docker container? If they are in separate containers (which they probably should be) then each container is separate. You will not have access to the binaries in the other container.

**Comment by ddubnyk** [comment]
I also have this issue actually. Using yt-dlp installed latest version from pip. 

Jellyfin 10.8.3 in docker container.

**Comment by ankenyr** [comment]
Is it installed in the docker container though? Can you show me evidence.of
that?

**Comment by ankenyr** [comment]
That is how it works right now. There is a bug possibly that is causing videos new videos to be marked as watched after upgrading to the latest jellyfin. https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/61

That being said, the way it works is the plugin sets all episodes to 1 (testing out 0 to fix the bug) and then a scheduled task comes in and looks at all videos within a season and sorts them by premiere date. This was neccesary as YT videos do not have episode numbers associated with them. A video could appear out of thin air from being marked private and then public again. Its upload date would not be affected. Sorting by that date makes sure there is an order and I update their index after sorting.
