### ISSUE TITLE
Can't install version 1.0.3.9

### ISSUE THREAD

**Issue by kitkw** [ankenyr/jellyfin-youtube-metadata-plugin#70]
I installed version 1.0.3.9, but it stays at version 1.0.3.8, and I can't scrape any metadata。
jellyfin version 10.8.4

![屏幕截图 2022-09-17 215055](https://user-images.githubusercontent.com/31963066/190860729-97fb6bc8-0c4a-4c44-8a13-aa0f22fd6c63.png)
![屏幕截图 2022-09-17 215113](https://user-images.githubusercontent.com/31963066/190860730-876cc92e-c70a-4e21-b31a-e814b75b3483.png)

**Comment by ankenyr** [comment]
Please provide logs, it looks installed, likely the config just has the wrong version.
