### ISSUE TITLE
Plugin overwrites nfo art poster with a poster frome episode instead of folder.jpg image

### ISSUE THREAD

**Issue by miguelarios** [ankenyr/jellyfin-youtube-metadata-plugin#74]
I have the following format for my folder hierarchy

`BBQ/%(channel)s [%(channel_id)s]/%(upload_date>%Y)s/%(channel)s - %(upload_date)s - %(title)s [%(id)s]/%(channel)s - %(upload_date)s - %(title)s [%(id)s].%(ext)s`

I am noticing that when YoutubeMetadata plugin downloads the metadata it always prefers an episode image instead of the folder image that I manually added. I even went into the nfo on the tvshow.nfo file and edited the art poster but it still gets overwritten.

How can I control this?

When i go to Refresh Metadata > Replace all Metadata and select to replace existing images it all comes back but then after a while I see the nfo gets edited and the image is back to an episode image not the folder.png image.

**Comment by ankenyr** [comment]
I believe in this case you just want to disable YoutubeMetadata for the responsible Image fetcher (TV Show, Season, Episode, etc)
<img width="2217" alt="image" src="https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/1542958/19e11967-4544-4a71-a2d7-55c407513c90">
