### ISSUE TITLE
Disable YT-DL online Scrapping

### ISSUE THREAD

**Issue by azukaar** [ankenyr/jellyfin-youtube-metadata-plugin#76]
I am using the plugin alongside a library that's already had their metadata populated in json files by YTDL. 
Since  it is useless to do it twice, I am trying to use the plugin in some "local only" fashion, but despite not having youtube-dl in its PATH, the plugin is always trying to reach for it, causing thousands of errors and slowing down the scan.
Anyway I can tell the plugin to be local only? 
Shouldn't it be local only by default anyway if the json files is already there?
Thanks you !

**Comment by ankenyr** [comment]
Did you disable the remote downloader in your libraries settings?

**Comment by azukaar** [comment]
Sorry do you mean this?
![image](https://user-images.githubusercontent.com/7872597/217543387-3a11be2d-ca10-4ea9-a3e8-5b4d7abd46f6.png)

**Comment by ankenyr** [comment]
No, sorry for not responding.
<img width="819" alt="image" src="https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/1542958/208e0d9e-1816-4f5f-808f-09eb95d1b9ee">

When you go into a library and change it's settings, there are a few sections for the metadata plugins. The `Reader` (top one in image) section as shown here is for local. The subsequent ones named `Download` (bottom one mentioning TV shows) is for downloading from remote.

**Comment by ankenyr** [comment]
Will mark this closed but feel free to reopen.
