### ISSUE TITLE
Jellyfin naming convention for poster images is not respected

### ISSUE THREAD

**Issue by BlueRocketMouse** [ankenyr/jellyfin-youtube-metadata-plugin#77]
I have been having some trouble with getting my YouTube library to correctly display poster images. It seems like instead of going by Jellyfin's image naming convention, it simply uses the first image it finds in each channel folder as the poster image regardless of filename. 

As far as I can tell, the problem only occurs in folders that have a [channel ID] in the name. Folders that don't have an ID in brackets will abide by the image filenames as expected. This issue also only applies to the poster images as far as I can tell. Backdrops and logos are always picked up normally as long as they are properly named. Here are some examples to better illustrate what I mean:

Channel [ID]
- fanart.jpg
- poster.jpg

fanart.jpg is used as both the backdrop and poster image.

Channel [ID]
- cover.jpg
- fanart.jpg

cover.jpg is used as the poster image and fanart.jpg is used as the backdrop image.

Channel [ID]
- a.jpg
- poster.jpg

a.jpg is used as the poster image.

Channel
- fanart.jpg
- poster.jpg

fanart.jpg is used as the backdrop image and poster.jpg is used as the poster image.

Jellyfin Server version 10.8.9
Plugin version 1.0.3.9 (though I have had this issue with older versions as well)
I have my root YouTube folder added as a Shows Library. All remote downloaders are disabled so only local metadata/images should be read.

**Comment by ankenyr** [comment]
I don't think this is an issue with my plugin. The image fetchers have a priority and the Embedded Image Extractor is the one that looks for specific files. You may wish to push that one above YoutubeMetadata's priority.
