### ISSUE TITLE
Thumbnails not correctly generated 

### ISSUE THREAD

**Issue by ATM-Tech** [ankenyr/jellyfin-youtube-metadata-plugin#8]
By default it seems that the plugin does not give videos the correct thumbnails, instead giving them a black thumbnail. However, if you go into "Edit Images,' you are able to select the correct thumbnail for the video to use. Shouldn't the video have the correct thumbnail to start with so the user doesn't have to select it themselves?

**Comment by ankenyr** [comment]
In your library settings if you click "Show advanced settings" is the "Movie Image Fetcher" checked on for YoutubeMetadata? If that is turned on mind telling me the other settings you have on? Also give an example of a video ID so I can test this.

**Comment by ATM-Tech** [comment]
I do have that turned on. Below are screenshots of my settings
Main Settings: 
![image](https://user-images.githubusercontent.com/4145112/82121075-109b1c00-9750-11ea-9c2d-e373e8c84c6f.png)
Fetcher Settings:
![image](https://user-images.githubusercontent.com/4145112/82121087-23155580-9750-11ea-9163-a22f0bb9184f.png)
This problem has affected every video I have tried but some examples would be umC_zUPGrp4, ho0tFjkwTkw, and RlHk8toVUDo

**Comment by ankenyr** [comment]
The latest release should solve this, mind confirming?
