### ISSUE TITLE
Cannot uninstall plugin version 1.0.3.8

### ISSUE THREAD

**Issue by JonasR** [ankenyr/jellyfin-youtube-metadata-plugin#80]
I get a 404, when trying to uninstall (or access settings, or disable) the plugin. All other plugins behave as expected.

I'm also not sure why I have version 1.0.3.8, since I just installed this not even a week ago and should have gotten 1.0.3.9, no? Is it related to https://github.com/jellyfin/jellyfin/issues/8081 by any chance?

Jellyfin is Version: 10.8.9 on Linux (running in a Truecharts container on TrueNAS-SCALE-22.12.2)

![image](https://user-images.githubusercontent.com/307785/232205376-5497d60d-a281-470a-83c1-c9fd76e53ce9.png)

**Comment by JonasR** [comment]
I tried installing 1.0.3.9 (again) and it confirms installation, prompting for a reboot. But when I do, I still only have 1.0.3.8 installed. Trying to install 1.0.3.8, it tells me that's the version I already have.

I also seem to be affected by https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/58 with the plugin running although it's not selected for the library in question, but I'm assuming that is unrelated.

**Comment by Kakoluz** [comment]
This just happened to me with a similar setup, combined with the previously mentioned issue, it fucked all media detection trying to scan it and crashing. Then when i went to uninstall it it didnt want to (404), and finally after manually removing the plugin from the filesystem so it wont load it managed to take down all plugin installing capabilities, so i cannot update or install any plugin.

Also, this all happened after it donwgraded itself from .9 to .8
