### ISSUE TITLE
Folder conventions & Youtube Profile Pictures

### ISSUE THREAD

**Issue by rdangdev** [ankenyr/jellyfin-youtube-metadata-plugin#81]
Similar to TubeArchivist, I would like the library for my Youtube folder to be Channel Name first with the appropriate profile picture. At the moment, with my scripts folder, it looks like this: [https://pixeldrain.com/u/PDdRZFKC](https://pixeldrain.com/u/PDdRZFKC)

The optimal structure for me would be:
Youtube/[Channel Name]/[Videos, Playlists, Audio-Only]/[video title]/video.mkv

All downloaded videos/channels are left inside those script folders. Are there any existing conventions or *arr-like interfaces that would help with sorting this?

Thanks!

**Comment by ankenyr** [comment]
You need to change your folder structure to match what Jellyfin wants.
https://jellyfin.org/docs/general/server/media/shows/
I don't believe I have control over this from the plugin itself. If you are not willing to rename the folder structure to continue to use TubeArchivist, you could setup a script to create symlinks to another folder that creates the structure needed I imagine.
