### ISSUE TITLE
Music library doesn't support?

### ISSUE THREAD

**Issue by marciglesias17** [ankenyr/jellyfin-youtube-metadata-plugin#82]
Hello,

This plugin does not support the Music library type?

It doesn't seem to be working for me.

**Comment by ankenyr** [comment]
The plugin supports music videos. I am unsure why you would want music when there are already lots of repositories for music metadata that are available for jellyfin.

**Comment by fabian-st** [comment]
@ankenyr most remixes/cover versions etc. aren't listed in any repository, being able to fetch metadata for this type of audio content (e.g. downloaded via TubeSync) would be very useful.
