### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by MatthK** [ankenyr/jellyfin-youtube-metadata-plugin#94]
I just installed Jellyfin in a docker container on Ubuntu.

Jellyfin runs so far fine. Then I tried to install your plugin, but somehow it doesn't show up under "My Plugins". I can see it under Repositories, but even after a few restarts, it still does not show in "My Plugins".

I did install yt-dlp in the docker container as per your instructions.

How can I get this installed?

**Comment by Intecancoder** [comment]
you need to go into "Catalog" and install it first, then restart Jellyfin
