### ISSUE TITLE
How should I organize my videos for this?

### ISSUE THREAD

**Issue by joekaiser** [ankenyr/jellyfin-youtube-metadata-plugin#95]
I have a "shows" library and am using the archive script from the library you link to. 

That script creates a folder for a playlist and each video in the playlist is a subfolder under that.

Jellyfin sees that structure as a show with each video being a season. An image for each folder is not generated by this plugin. Images for each video are though.

How do you organize your library? Maybe I'm not understanding something how how it works.

Thanks 😊

**Comment by ankenyr** [comment]
https://github.com/ankenyr/jellyfin-youtube-metadata-plugin#file-naming-requirements documents the file naming requirement. Other than that organize it like TV shows iirc. I organize by channel>year>episode>files

**Comment by joekaiser** [comment]
I'm sorry, I'm probably over thinking this, but It doesn't make sense to me :/

If I download "playlist1" from "creator", then the structure I'm using is creator>playlist1>video>files  

where "video" and "files" are the output from TheFrenchGhosty's Ultimate YouTube-DL Scripts

**Comment by joekaiser** [comment]
:shrug: I deleted the library and created it again. Things are working as I expect. Thanks for the project :)
