### ISSUE TITLE
Can't uninstall youtubemetadata

### ISSUE THREAD

**Issue by alscaldas** [ankenyr/jellyfin-youtube-metadata-plugin#96]
Hello,

I installed this plugin and now I'm trying to uninstall it but it doesn't work. It keeps spinning as if it was uninstalling but nothing happens. No error msg, nothing. Am I maybe missing something?

**Comment by ankenyr** [comment]
It may be better to ask on the jellyfin repo. The plugin itself does not control its ability to be uninstalled.
